apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-delta
  namespace: kafka
  labels:
    app: kafka-delta
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kafka-delta
  template:
    metadata:
      labels:
        app: kafka-delta
    spec:
      containers:
      - name: kafka-delta
        image: andreyolv/kafka-sink:1.1
        command:
        - "python3"
        - "app/kafka-delta-full.py"
        resources:
          requests:
            cpu: "500m"
            memory: 1Gi
          limits:
            cpu: "1"
            memory: 2Gi
        imagePullPolicy: Always
      #imagePullSecrets:
      #  - name: acr-secret