apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-ui
  namespace: kafka-strimzi
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/kafka-ui
      sourceRef:
        kind: GitRepository
        name: provectus
        namespace: flux-system
  releaseName: kafka-ui
  values:
    service:
      type: ClusterIP
      port: 8080
    #envFrom:
    #- configMapRef:
    #    name: env-kafka-ui    
    env: 
    - name: KAFKA_CLUSTERS_0_NAME
      value: gac-cdc
    - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
      value: http://gac-cdc-kafka-bootstrap.kafka-strimzi.svc.cluster.local:9092
    - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
      value: http://schema-registry-cp-schema-registry.kafka-strimzi.svc.cluster.local:8081
    - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME
      value: connect-cluster
    - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS
      value: http://connect-cluster-connect-api.kafka-strimzi.svc.cluster.local:8083 
