apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: "inventory-connector"
  namespace: kafka
  labels:
    strimzi.io/cluster: connect-cluster
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    #key.converter: io.confluent.connect.avro.AvroConverter
    #key.converter.schema.registry.url: http://schema-registry-cp-schema-registry:8081
    #value.converter: io.confluent.connect.avro.AvroConverter
    #value.converter.schema.registry.url: http://schema-registry-cp-schema-registry:8081
    database.hostname: mysql.mysql
    database.port: "3306"
    database.user: "root"
    database.password: "debezium"
    database.server.id: "184054"
    database.server.name: "dbserver1"
    database.whitelist: "inventory" # vários "inventory.table1, inventory.table2, ..."
    #table.include.list: "products"
    #query: "SELECT * FROM .. WHERE column1='Abc'"
    database.history.kafka.bootstrap.servers: "my-cluster-kafka-bootstrap:9092"
    database.history.kafka.topic: "sddl-dbhistory-cdc-tables"
    include.schema.changes: "true"
    database.allowPublicKeyRetrieval: "true"
    #topic.creation.enable: "true"
    #topic.creation.default.replication.factor: 3
    #topic.creation.default.partitions: 1
    #tranform show only after changes, without tranform show both before and after
    transforms: "unwrap"
    transforms.unwrap.type: "io.debezium.transforms.ExtractNewRecordState"
    transforms.unwrap.add.headers: "db"
    transforms.unwrap.add.fields: "op,table,source.ts_ms"
    transforms.unwrap.drop.tombstones: "false"
    transforms.unwrap.delete.handling.mode: "rewrite"
