apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: '6.47.1'
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: monitoring
      interval: 1m
