apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: gac
  labels:
    strimzi.io/cluster: gac-cdc
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Example ACL rules for producing to topic my-topic
      - resource:
          type: topic
          name: dbserver1.inventory.products
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
        host: "*"
      # Example ACL rules for consuming from my-topic using consumer group my-group
      - resource:
          type: topic
          name: dbserver1.inventory.products
          patternType: literal
        operations:
          - Describe
          - Read
        host: "*"
      - resource:
          type: group
          name: my-group
          patternType: literal
        operations:
          - Read
        host: "*"
